### ISSUE TITLE
编译后产生的空格对浏览器解析css有影响

### ISSUE THREAD

**Issue by lihsai0** [cyyjs/scss2css-vscode#3]
# 运行环境
系统 OS X 10。12.6
VS Code Version 1.17.0 (1.17.0)
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

# 问题重现
## scss代码
``` scss

  .tooltip-content {
    position: absolute;
    top: 30px;
    left: 40px;
    display: none;
    background: #ffffff;
    z-index: 30;

    &::before {
      box-sizing: border-box;
      content: "";
      width: 0;
      height: 0;
      border-style: solid;
      border-width: 0 10px 10px 10px;
      border-color: transparent transparent #ffffff transparent;
      position: absolute;
      top: -10px;
      left: 30px;
    }
  }
```

## 编译后的css代码
``` css
.tooltip-content::before {
  box-sizing: border-box;
  content: "";
/* ******************** */
  width:  0;
  height:  0;
  border-style:  solid;
  border-width:  0 10px 10px 10px;
  border-color:  transparent transparent #ffffff transparent;
  /* ******************** */
  position: absolute;
  top: -10px;
  left: 30px;
}
```

# 问题说明

`*`符号中间的部分，`:`后有两个空格。存在这两个空格时，`::before`失效。删除后正常，而且手打多少个空格都没有问题。

# 附图

## 未对编译后的css修改

![image](https://user-images.githubusercontent.com/17806506/31535170-a84ba2de-afbf-11e7-8360-8df881972f29.png)

## 删除编译后的css中的空格

![image](https://user-images.githubusercontent.com/17806506/31535185-bdf03816-afbf-11e7-8969-219a4c9ffd40.png)

**Comment by cyyjs** [comment]
我尝试编译你的scss代码，并未出现空格。

**Comment by lihsai0** [comment]
对不起，我的锅，应该贴上整个代码。尝试下这个，这个是我完整的代码：
``` scss
.tooltip-component {
  position: relative;
  
  .tooltip-hide {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    z-index: 20;
    width: 100vw;
    height: 100vh;
  }

  .tooltip-content {
    position: absolute;
    top: 30px;
    left: 40px;
    display: none;
    background: #ffffff;
    z-index: 30;

    &::before {
      box-sizing: border-box;
      content: "";
      width: 0;
      height: 0;
      border-style: solid;
      border-width: 0 10px 10px 10px;
      border-color: transparent transparent #ffffff transparent;
      position: absolute;
      top: -10px;
      left: 30px;
    }
  }

  input[type=checkbox] {
    // display: none;

    &:checked{

      & ~ .tooltip-hide{
        display: block;
      }

      & ~ .tooltip-content {
        display: block;
      }

    }

  }

}
```
